name: CI
on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - run: npm ci

      - run: npm test --coverage
        env:
          CI: true

      - name: Upload Test Coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage

      - name: Build Post Review
        if: github.event_name == 'push'
        run: npm run build

      - name: Upload Build
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: npx surge --project ./build --domain samuelclerod.surge.sh
        env:
          SURGE_LOGIN: ${{secrets.SURGE_LOGIN}}
          SURGE_TOKEN: ${{secrets.SURGE_TOKEN}}
